/* DO NOT EDIT THIS FILE
 * - vm_shell.h (Part of StrawHat VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2024
 *
 *   Provides the prototype to grant shell access to StrawHat functions.
 */

#ifndef VM_SHELL_H
#define VM_SHELL_H

extern int g_debug_mode;
void shell(); // Run the Virtual System with Shell Access

#endif
